"""create users table with varchar length

Revision ID: 29513ae2f641
Revises: 6a5f19773024
Create Date: 2025-09-07 17:55:50.161709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '29513ae2f641'
down_revision: Union[str, Sequence[str], None] = '6a5f19773024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_teste'), table_name='users')
    op.drop_column('users', 'teste')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('teste', mysql.VARCHAR(length=255), nullable=True))
    op.create_index(op.f('ix_users_teste'), 'users', ['teste'], unique=True)
    # ### end Alembic commands ###
